---
notifications:
  slack:
    defaultChannel: "bbgo"
    errorChannel: "bbgo-error"

exchangeStrategies:
  - on: max
    rebalance:
      interval: 1d
      baseCurrency: TWD
      ignoreLocked: true
      targetWeights:
        BTC: 40%
        ETH: 20%
        MAX: 10%
        USDT: 15%
        TWD: 15%
      threshold: 2%
      sliceSize: 0.1
      updateInterval: 10s
      verbose: true
      dryRun: false
